name: Standard CI

# trigger
on: push
jobs:

    build-test:

        name: Build, Test and deploy
        runs-on: ubuntu@latest 

        steps:

            - name: Checkout latest code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
                
            - name : Run Lint
              run: npm run lint

            - name : Run Build
              run: npm run build

            - name : Run Tests
              run: npm run test
            
            - name: Run Deploy
              run: npm run deploy
